name: NuGet Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: List items
        run: ls -l

      - name: Restore dependencies
        run: dotnet restore RouteDispatcher.sln
        working-directory: ../

      - name: Build
        run: dotnet build RouteDispatcher.sln --configuration Release --no-restore
        working-directory: ../

      - name: Pack
        run: dotnet pack src/RouteDispatcher/RouteDispatcher.csproj --configuration Release --no-build
        working-directory: ../

      - name: Push to NuGet
        run: dotnet nuget push src/RouteDispatcher/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
